### ISSUE TITLE
Internet gone after starting the script

### ISSUE THREAD

**Issue by Diamantino-Op** [ObscenityIB/creeper#15]
Is it normal for internet to go down and not connecting for 10mins after starting the program?

**Comment by ObscenityIB** [comment]
only If your connection is very slow.
the scan is set to 5kpps, about 1Mbit/s.

you can edit the script and change the line 82 from:
`sudo masscan --excludefile exclude.conf -p 25565 --rate 5000 -oG ./creeper-logs/creeper-scan-$logtime.log $1 2>&1 | tee -a ./creeper-logs/creeper-logger-$logtime.log`
to something like:
`sudo masscan --excludefile exclude.conf -p 25565 --rate 2500 -oG ./creeper-logs/creeper-scan-$logtime.log $1 2>&1 | tee -a ./creeper-logs/creeper-logger-$logtime.log`

Just lower the `--rate` part.

Maybe even smaller, depending on how slow your internet is.
Of course this will make the scan take longer, but it should stop weaker connections from dying.

If it still dies after this, check your router settings if there is a firewall with a packet speed limit or something similar.

**Comment by ObscenityIB** [comment]
Stale, Closing.

**Comment by 0x3C50** [comment]
omg who would have thought that scanning 5k ips a fucking second would crash the internet!!!! :scream: :fearful:
