### ISSUE TITLE
using --mcc fails to run MCC

### ISSUE THREAD

**Issue by tetrabyyte** [ObscenityIB/creeper#16]
**Describe the bug**
after every scan it attempts to use MCC to join the server but fails saying "Cannot open assembly 'MinecraftClient': File does not contain a valid CIL image."

**To Reproduce**
1. Install creeper
2. install latest MCC
3. Type './creeper.sh example.0.0.0/8 --mcc'

**Screenshots**

![U1vK7Skd7j](https://user-images.githubusercontent.com/116705399/197946273-2ec2671e-1e9d-45f2-a6e3-53e959c9d860.png)

**Desktop (please complete the following information):**
 - OS, Distro and version: openSUSE Leap 15.3
 - Script Version v1.2.0.0 

**Additional context**
someone had the same problem using MCC by itself https://github.com/MCCTeam/Minecraft-Console-Client/issues/2106
the problem just seems to be MCC doesnt use mono to run anymore, https://github.com/MCCTeam/Minecraft-Console-Client/issues/2106#issuecomment-1217221509
fixing this problem would also fix the other open issue with microsoft accounts since MCC supports ms accounts now

**Comment by ObscenityIB** [comment]
Hi, thanks for letting me know.
It has been a while since I had updated this one since the whole MS fiasco.

I'll look into the changes to MCC and implement an update.
