### ISSUE TITLE
Your account joined my server BEFORE I was about to put a whitelist on and nearly gave me a heart-attack

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [ObscenityIB/creeper#8]
Thank you for scaring the crap out of me
![2021-09-06_03 21 10](https://user-images.githubusercontent.com/86382621/132186155-ef312ee8-53a5-48b8-8f99-ca96f4ea2085.png)

I did add a whitelist btw

**Comment by ObscenityIB** [comment]
Hahaha, nice.
